<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="lidar_radius" value="0.0445"/>
    <xacro:property name="lidar_height" value="0.072"/>
    <xacro:property name="lidar_offset_x" value="0.215"/>
    <xacro:property name="lidar_samples" value="1875"/>
    <xacro:property name="lidar_lasers" value="16"/>
    <xacro:property name="lidar_horizontal_min_angle" value="-${pi}"/>
    <xacro:property name="lidar_horizontal_max_angle" value="${pi}"/>
    <xacro:property name="lidar_vertical_min_angle" value="-${20*pi/180}"/>
    <xacro:property name="lidar_vertical_max_angle" value="${20*pi/180}"/>
    <xacro:property name="lidar_mass" value="0.6"/>

    <material name="lidar">
        <color rgba="0 0 0.55 1"/>
    </material>

    <joint name="lidar_joint" type="fixed">
        <parent link="body"/>
        <child link="lidar"/>
        <origin xyz="${lidar_offset_x} 0 ${body_height/2+lidar_height/2}"/>
    </joint>
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
            <material name="lidar"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" radius="${lidar_radius}" length="${lidar_height}">
            <origin/>
        </xacro:inertial_cylinder>
    </link>
</robot>
