<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="body_length" value="0.84"/>
    <xacro:property name="body_width" value="0.66"/>
    <xacro:property name="body_height" value="0.32"/>
    <xacro:property name="body_mass" value="30"/>
    <xacro:property name="wheel_radius" value="0.125"/>
    <xacro:property name="wheel_width" value="0.07"/>
    <xacro:property name="wheel_offset_x" value="0.265"/>
    <xacro:property name="wheel_offset_y" value="0.275"/>
    <xacro:property name="wheel_offset_z" value="0.015"/>
    <xacro:property name="wheel_mass" value="2"/>
    <xacro:property name="tower_height" value="0.37"/>
    <xacro:property name="tower_width" value="0.19"/>
    <xacro:property name="tower_mass" value="1.1643"/>

    <material name="body">
        <color rgba="0.12 0.56 1 1"/>
    </material>
    <material name="wheel">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="tower">
        <color rgba="1 1 1 1"/>
    </material>


    <link name="base_link"></link>

    <!-- Body -->
    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 ${body_height/2+wheel_radius-wheel_offset_z}"/>
    </joint>
    <link name="body">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="body"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}">
            <origin/>
        </xacro:inertial_box>
    </link>

    <!-- Wheels -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="left_wheel"/>
        <origin xyz ="${wheel_offset_x} ${wheel_offset_y} -${body_height/2-wheel_offset_z}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="wheel"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}">
            <origin/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="right_wheel"/>
        <origin xyz ="${wheel_offset_x} -${wheel_offset_y} -${body_height/2-wheel_offset_z}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="wheel"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}">
            <origin/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="rear_left_wheel_joint" type="fixed">
        <parent link="body"/>
        <child link="rear_left_wheel"/>
        <origin xyz ="-${wheel_offset_x} ${wheel_offset_y} -${body_height/2-wheel_offset_z}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="wheel"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}">
            <origin/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="rear_right_wheel_joint" type="fixed">
        <parent link="body"/>
        <child link="rear_right_wheel"/>
        <origin xyz ="-${wheel_offset_x} -${wheel_offset_y} -${body_height/2-wheel_offset_z}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="wheel"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_width}">
            <origin/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="odom_joint" type="fixed">
  <parent link="odom"/>
  <child link="base_link"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="odom"/>

    <!-- Tower -->
    <joint name="tower_joint" type="fixed">
        <parent link="body"/>
        <child link="tower"/>
        <origin xyz="0 0 ${body_height/2+tower_height/2}"/>
    </joint>
    <link name="tower">
        <visual>
            <geometry>
                <box size="${tower_width} ${tower_width} ${tower_height}"/>
            </geometry>
            <material name="tower"/>
        </visual>
        <collision>
            <geometry>
                <box size="${tower_width} ${tower_width} ${tower_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${tower_mass}" x="${tower_width}" y="${tower_width}" z="${tower_height}">
            <origin/>
        </xacro:inertial_box>
    </link>
</robot>
