controller_manager:
  ros__parameters:
    controller_list:
      - name: "front_steering_controller"
        type: "position_controllers/JointTrajectoryController"
        joints:
          - "front_steering_joint"
        pid:
          p: 1.0
          i: 0.0
          d: 0.1
          
      - name: "rear_steering_controller"
        type: "position_controllers/JointTrajectoryController"
        joints:
          - "rear_steering_joint"
        pid:
          p: 1.0
          i: 0.0
          d: 0.1
          
      - name: "front_left_wheel_controller"
        type: "effort_controllers/JointPositionController"
        joints:
          - "front_left_wheel_joint"
          
      - name: "front_right_wheel_controller"
        type: "effort_controllers/JointPositionController"
        joints:
          - "front_right_wheel_joint"
          
      - name: "rear_left_wheel_controller"
        type: "effort_controllers/JointPositionController"
        joints:
          - "rear_left_wheel_joint"
          
      - name: "rear_right_wheel_controller"
        type: "effort_controllers/JointPositionController"
        joints:
          - "rear_right_wheel_joint"