controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.55
    wheel_radius: 0.12
    use_stamped_vel: true          # Изменено на true
    enable_odom_tf: true           # Убедитесь, что это true
    pose_covariance_diagonal: [0.001, 0.001, 0.01, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.01, 0.0, 0.0, 0.01]
